### ISSUE TITLE
Hot-fix packages using NumPy to require <2 ?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-repodata-patches-feedstock#516] opened 2023-08-22 20:54 UTC
As brought up in issue ( https://github.com/conda-forge/scikit-learn-feedstock/issues/227 ) ( in particular comment: https://github.com/conda-forge/scikit-learn-feedstock/issues/227#issuecomment-1688323555 ), for old packages we may not have `numpy` dependencies in `run` correctly constrained to ensure `numpy` `2` isn't pulled in by accident. Some proposed next steps:

* Audit repodata to find where `numpy` upper bounds are undefined or too loose
* Submit a repodata patch to fix those dependencies to be more tightly constrained
* Make sure feedstocks are rebuilt with correct `numpy` constraint (if that hasn't already happened)
* ?

Please suggest other steps or revise existing ones

cc @conda-forge/core

**Comment by h-vetinari** [comment] 2024-04-20 01:00
>  * Audit repodata to find where `numpy` upper bounds are undefined or too loose
>  * Submit a repodata patch to fix those dependencies to be more tightly constrained

I opened https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/712

>  * Make sure feedstocks are rebuilt with correct `numpy` constraint (if that hasn't already happened)

For packages compiling against numpy, we've had a run-export for 2 years (https://github.com/conda-forge/numpy-feedstock/commit/bca09161e46d1a986e061e4aaf6a21d8eb809a98), so this should not be an issue. The problem is that feedstocks with a run-only dependence will do stuff like `- numpy >=1.16`. This is hard to catch.

We _could_ address this in the piggyback, but it's not even clear to me that we'd need to change it, if the package builds successfully against 2.0.

**Comment by h-vetinari** [comment] 2024-05-13 13:08
There isn't a huge amount left to do here after #728 I think. However, obviously more packages can get added in https://github.com/numpy/numpy/issues/26191, and also some packages which are currently missing a known lowest numpy 2.0-compatible version should be updated in the patch_yaml as those versions become known, see:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/28be10e78f83069230c5e872cf2af543fa9329e3/recipe/patch_yaml/numpy2_unknown_lower_bound.yaml#L1-L6

For those reasons, I suggest to keep the issue open.

**Comment by beckermr** [comment] 2024-05-13 13:47
SGTM! I am going to draft an announcement explaining where to put patches and what we did.

**Comment by jakirkham** [comment] 2024-05-13 17:51
Should we roll that announcement into a general NumPy 2 announcement?

Repodata patching is presumably only on of a few things for NumPy 2 users & maintainers will care about

**Comment by hmaarrfk** [comment] 2024-09-22 18:43
I feel like we can close this issue now right?

**Closed** 2024-10-15 07:40 UTC
